# Generated by Django 5.2.7 on 2025-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('barrio_residencia', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('inicial', 'Inicial'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')])),
            ],
        ),
    ]
