# Generated by Django 5.2.7 on 2025-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estudiante_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(choices=[('inicial', 'N1'), ('intermedio', 'N2'), ('avanzado', 'N3')]),
        ),
    ]
