# Generated by Django 5.2.7 on 2025-10-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_estudiante_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(choices=[('n1', 'inicial'), ('n2', 'intermedio'), ('n3', 'avanzado')], default=('n1', 'inicial'), max_length=2),
        ),
    ]
