# Generated by Django 5.2.7 on 2025-10-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_estudiante_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('puntaje_docente', models.FloatField(default=3.0)),
                ('ige', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
