# Generated by Django 5.2.7 on 2025-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('n1', 'inicial'), ('n2', 'intermedio'), ('n3', 'avanzado')], default=('n1', 'inicial'), max_length=2)),
                ('horas_catedra', models.IntegerField()),
                ('codigo', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='docente',
            name='ige',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel',
        ),
    ]
